### ISSUE TITLE
arni_processing: rating a node beeing not alive while he is

### ISSUE THREAD

**Issue by gmwe** [ROS-PSE/arni#10]
#### setup:

> roslaunch arni_core test_1_steady.launch

will have one publisher on /forest with ~100Hz
#### bug description

/statistics_rated shows:

```
seuid: t!/forest
[...]
    statistic_type: frequency
    actual_value: ['99.9440327908']
    expected_value: ['[80, 120]']
    state: [3]
  - 
    statistic_type: alive
    actual_value: ['True']
    expected_value: ['True']
    state: [2]
```

while it also regularily shows

```
seuid: t!/forest
host: ''
window_start: 
  secs: 1411321640
  nsecs: 902513027
window_stop: 
  secs: 1411321960
  nsecs: 902126073
rated_statistics_entity: 
  - 
    statistic_type: alive
    actual_value: ['False']
    expected_value: ['True']
    state: [1]
```

which is incorrect data because the node is still alive.
