### ISSUE TITLE
incorrect bandwidth from monitoring_node 

### ISSUE THREAD

**Issue by gmwe** [ROS-PSE/arni#2]
## Szenario

> **roslaunch arni_core test_1_steady.launch**

Publisher **/steady_tree** publiziert mit ~10MB/s auf dem Topic **/forest**. 
**/ninja_turtle** subscribed **/forest**.

> **rostopic bw /forest**
> average: 10.29MB/s
>     mean: 1.02MB min: 1.02MB max: 1.02MB window: 100
## Fehlerbeschreibung

Topic /statistic_rated zeigt nur ca 0.25MB/s an

> **rostopic echo /statistic_rated**

```
seuid: t!/forest
host: ''
window_start: 
  secs: 1411054745
  nsecs: 339412927
window_stop: 
  secs: 1411054749
  nsecs: 423893928
rated_statistics_entity: 
  - 
    statistic_type: bandwidth
    actual_value: ['250731.488223']
    expected_value: ['None']
    state: [2]

seuid: c!/ninja_turtle!/forest!/steady_tree
host: ''
window_start: 
  secs: 1411054749
  nsecs: 423893928
window_stop: 
  secs: 1411054753
  nsecs: 525305986
rated_statistics_entity: 
  - 
    statistic_type: bandwidth
    actual_value: ['249696.442473']
    expected_value: ['[8001000, 15001000]']
    state: [1]
```
